# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sarcasm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sarcasm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsarcasm.proto\x12\x04\x64\x65mo\" \n\x10SarcasticRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"8\n\x11SarcasticResponse\x12\x10\n\x08original\x18\x01 \x01(\t\x12\x11\n\tsarcastic\x18\x02 \x01(\t2E\n\x07Sarcasm\x12:\n\x07\x43onvert\x12\x16.demo.SarcasticRequest\x1a\x17.demo.SarcasticResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sarcasm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SARCASTICREQUEST']._serialized_start=23
  _globals['_SARCASTICREQUEST']._serialized_end=55
  _globals['_SARCASTICRESPONSE']._serialized_start=57
  _globals['_SARCASTICRESPONSE']._serialized_end=113
  _globals['_SARCASM']._serialized_start=115
  _globals['_SARCASM']._serialized_end=184
# @@protoc_insertion_point(module_scope)
